### ISSUE TITLE
Undefined references

### ISSUE THREAD

**Issue by ajelenak-thg** [bbaggerman/irig106utils#3]
With #2 corrected, building using the GCC Makefile fails because of two undefined references:

1. ``i106udprcv.c:226: undefined reference to `enI106Ch10OpenStreamRead'``
1. ``i106udprcv.c:237: undefined reference to `enI106Ch10OpenPcapRead'``

**Comment by br0kej** [comment]
I am currently receiving the same error and managed to work around it by executing the make file on specific utils. 

For example:
`make idmp1553 idmp429 idmpins i106stat

**Comment by ajelenak** [comment]
@br0kej Thanks! This is issue can be closed.
